item {
    id: 1
    name: 'amountWord'
}

item {
    id: 2
    name: 'amountNumber'
}

item {
    id: 3
    name: 'date'
}

item {
    id: 4
    name: 'validPeriod'
}

item {
    id: 5
    name: 'ABArouting'
}

item {
    id: 6
    name: 'signature'
}



